CREATE TABLE student_class_memberships (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL,
  student_id BIGINT NOT NULL,
  school_id BIGINT NOT NULL,
  grade_id BIGINT NOT NULL,
  class_id BIGINT NOT NULL,
  is_current TINYINT(1) NOT NULL DEFAULT 1,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  joined_at DATETIME(3) NOT NULL,
  left_at DATETIME(3) NULL,
  created_by BIGINT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  KEY idx_scm_student_current (student_id, is_current, status),
  KEY idx_scm_class_current (class_id, is_current, status),
  KEY idx_scm_grade_current (grade_id, is_current, status),
  CONSTRAINT fk_scm_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_scm_student FOREIGN KEY (student_id) REFERENCES users(id),
  CONSTRAINT fk_scm_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_scm_grade FOREIGN KEY (grade_id) REFERENCES grades(id),
  CONSTRAINT fk_scm_class FOREIGN KEY (class_id) REFERENCES classes(id),
  CONSTRAINT fk_scm_created_by FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE teacher_class_course_assignments (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL,
  teacher_id BIGINT NOT NULL,
  school_id BIGINT NOT NULL,
  grade_id BIGINT NOT NULL,
  class_id BIGINT NOT NULL,
  course_id BIGINT NOT NULL,
  is_current TINYINT(1) NOT NULL DEFAULT 1,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  effective_from DATETIME(3) NOT NULL,
  effective_to DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  KEY idx_tcca_teacher_current (teacher_id, is_current, status),
  KEY idx_tcca_class_course_current (class_id, course_id, is_current, status),
  CONSTRAINT fk_tcca_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_tcca_teacher FOREIGN KEY (teacher_id) REFERENCES users(id),
  CONSTRAINT fk_tcca_school FOREIGN KEY (school_id) REFERENCES schools(id),
  CONSTRAINT fk_tcca_grade FOREIGN KEY (grade_id) REFERENCES grades(id),
  CONSTRAINT fk_tcca_class FOREIGN KEY (class_id) REFERENCES classes(id),
  CONSTRAINT fk_tcca_course FOREIGN KEY (course_id) REFERENCES courses(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

