CREATE TABLE practice_session_question_reviews (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL,
  class_id BIGINT NOT NULL,
  course_id BIGINT NOT NULL,
  student_user_id BIGINT NOT NULL,
  session_id BIGINT NOT NULL,
  session_question_id BIGINT NOT NULL,
  teacher_user_id BIGINT NOT NULL,
  review_comment TEXT NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uk_psqr_tenant_question_teacher (tenant_id, session_question_id, teacher_user_id),
  KEY idx_psqr_class_course_student (tenant_id, class_id, course_id, student_user_id),
  KEY idx_psqr_session_question (session_id, session_question_id),
  CONSTRAINT fk_psqr_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_psqr_class FOREIGN KEY (class_id) REFERENCES classes(id),
  CONSTRAINT fk_psqr_course FOREIGN KEY (course_id) REFERENCES courses(id),
  CONSTRAINT fk_psqr_student_user FOREIGN KEY (student_user_id) REFERENCES users(id),
  CONSTRAINT fk_psqr_session FOREIGN KEY (session_id) REFERENCES practice_sessions(id),
  CONSTRAINT fk_psqr_session_question FOREIGN KEY (session_question_id) REFERENCES practice_session_questions(id),
  CONSTRAINT fk_psqr_teacher_user FOREIGN KEY (teacher_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
